#include "CMG_AutoGenerated.h"

CMG_AutoGenerated::CMG_AutoGenerated(std::vector<frc::Command*> commands) {

	/*
	 * Here we're iterating through all commands added during construction and adding
	 * them to our sequential command listing. We could optionally allow configuration
	 * of parallel and sequential commands respectively but nah.
	 */
	for(unsigned int i = 0; i < commands.size(); i++){
		AddSequential(commands[i]);
	}
}
