#ifndef CMG_AutoGenerated_H
#define CMG_AutoGenerated_H

#include <WPILib.h>
#include <vector>
#include <Commands/CommandGroup.h>
#include <Commands/Command.h>

class CMG_AutoGenerated : public frc::CommandGroup {
public:
	CMG_AutoGenerated(std::vector<frc::Command*> commands);
};

#endif  // CMG_AutoGenerated_H
